name: CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

env:
  app_name: app_${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Build App
        run: |
         docker build -t main:${{ env.app_name }} . &&
         docker image save main:${{ env.app_name }} -p ${{ env.app_name }}
                 
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ env.app_name }}.tgz
          retention-days: 30
          
      - name: Telegram Notify
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ TELEGRAM_CHAT_ID.TELEGRAM_CHAT_ID }}
          token: ${{ TELEGRAM_CHAT_ID.TELEGRAM_TOKEN }}
          message: |
            Repository: ${{ github.repository }}
            Actor: ${{ github.actor }}
            Event: ${{ github.event_name }}
            Job status: ${{ job.status }}
